const GoogleStrategy = require('passport-google-oauth20').Strategy;
const TwitterStrategy = require('passport-twitter').Strategy;
const { User } = require('./models');

module.exports = (passport) => {
  // We won't use sessions; passport just returns user via callback
    if (process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET) {
        passport.use(new GoogleStrategy({
              clientID: process.env.GOOGLE_CLIENT_ID,
                    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
                          callbackURL: process.env.GOOGLE_CALLBACK_URL || 'http://localhost:4000/auth/google/callback'
                              }, async (accessToken, refreshToken, profile, done) => {
                                    try {
                                            const email = profile.emails?.[0]?.value;
                                                    let user = await User.findOne({ provider: 'google', providerId: profile.id });
                                                            if (!user && email) user = await User.findOne({ email });
                                                                    if (!user) {
                                                                              user = await User.create({
                                                                                          email,
                                                                                                      name: profile.displayName,
                                                                                                                  provider: 'google',
                                                                                                                              providerId: profile.id,
                                                                                                                                          emailVerified: email ? true : false,
                                                                                                                                                      needsPasswordSetup: true
                                                                                                                                                                });
                                                                                                                                                                        } else {
                                                                                                                                                                                  user.provider = 'google';
                                                                                                                                                                                            user.providerId = profile.id;
                                                                                                                                                                                                      user.needsPasswordSetup = !user.passwordHash;
                                                                                                                                                                                                                await user.save();
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                return done(null, user);
                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                              done(err, null);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        }));
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            if (process.env.TWITTER_CONSUMER_KEY && process.env.TWITTER_CONSUMER_SECRET) {
                                                                                                                                                                                                                                                                passport.use(new TwitterStrategy({
                                                                                                                                                                                                                                                                      consumerKey: process.env.TWITTER_CONSUMER_KEY,
                                                                                                                                                                                                                                                                            consumerSecret: process.env.TWITTER_CONSUMER_SECRET,
                                                                                                                                                                                                                                                                                  callbackURL: process.env.TWITTER_CALLBACK_URL || 'http://localhost:4000/auth/twitter/callback',
                                                                                                                                                                                                                                                                                        includeEmail: true
                                                                                                                                                                                                                                                                                            }, async (token, tokenSecret, profile, done) => {
                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                          const email = profile.emails?.[0]?.value;
                                                                                                                                                                                                                                                                                                                  let user = await User.findOne({ provider: 'twitter', providerId: profile.id });
                                                                                                                                                                                                                                                                                                                          if (!user && email) user = await User.findOne({ email });
                                                                                                                                                                                                                                                                                                                                  if (!user) {
                                                                                                                                                                                                                                                                                                                                            user = await User.create({
                                                                                                                                                                                                                                                                                                                                                        email: email || `tw_${profile.username}@no-email.local`,
                                                                                                                                                                                                                                                                                                                                                                    name: profile.displayName || profile.username,
                                                                                                                                                                                                                                                                                                                                                                                provider: 'twitter',
                                                                                                                                                                                                                                                                                                                                                                                            providerId: profile.id,
                                                                                                                                                                                                                                                                                                                                                                                                        emailVerified: !!email,
                                                                                                                                                                                                                                                                                                                                                                                                                    needsPasswordSetup: true
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                user.provider = 'twitter';
                                                                                                                                                                                                                                                                                                                                                                                                                                                          user.providerId = profile.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user.needsPasswordSetup = !user.passwordHash;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await user.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return done(null, user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            done(err, null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };