import React, { useEffect, useState } from 'react';
import HostForm from './HostForm';
import AdvertiserForm from './AdvertiserForm';
import HamburgerMenu from './HamburgerMenu';
import WalletConnectBtn from './WalletConnectBtn';
import api from '../api';

/**
 * Dashboard component
  * - Shows welcome header
   * - Offers Host / Advertiser cards
    * - Loads existing host profile (if any)
     * - Integrates WalletConnect button
      */
      export default function Dashboard({ user }) {
        const [view, setView] = useState(null); // 'host' | 'advertiser' | null
          const [menuOpen, setMenuOpen] = useState(false);
            const [profile, setProfile] = useState(null);
              const [loadingProfile, setLoadingProfile] = useState(true);

                useEffect(() => {
                    let mounted = true;
                        (async () => {
                              try {
                                      const res = await api.get('/api/hosts/me');
                                              if (!mounted) return;
                                                      setProfile(res.data.profile || null);
                                                            } catch (err) {
                                                                    // ignore if no profile
                                                                            setProfile(null);
                                                                                  } finally {
                                                                                          if (mounted) setLoadingProfile(false);
                                                                                                }
                                                                                                    })();
                                                                                                        return () => { mounted = false; };
                                                                                                          }, []);

                                                                                                            const handleWalletConnected = async (address) => {
                                                                                                                try {
                                                                                                                      await api.post('/api/users/wallet', { address });
                                                                                                                            // optionally update user UI or toast
                                                                                                                                } catch (e) {
                                                                                                                                      console.error('save wallet failed', e);
                                                                                                                                            alert('Failed to save wallet address to server');
                                                                                                                                                }
                                                                                                                                                  };

                                                                                                                                                    return (
                                                                                                                                                        <div className="dashboard">
                                                                                                                                                              <HamburgerMenu open={menuOpen} onClose={() => setMenuOpen(false)} onOpen={() => setMenuOpen(true)} />
                                                                                                                                                                    <div className="dashboard-top" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                            <div>
                                                                                                                                                                                      <h2 style={{ fontFamily: 'Times New Roman', margin: 0 }}>Welcome, {user?.name || user?.email || 'friend'}</h2>
                                                                                                                                                                                                <div style={{ fontSize: 13, color: '#666' }}>{user?.role ? `Role: ${user.role}` : 'Choose a role to get started'}</div>
                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                                                                                                                                                                                                                          <WalletConnectBtn onConnected={handleWalletConnected} />
                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                className="hamburger"
                                                                                                                                                                                                                                                            onClick={() => setMenuOpen((o) => !o)}
                                                                                                                                                                                                                                                                        aria-label="Menu"
                                                                                                                                                                                                                                                                                    style={{ fontSize: 20, background: 'transparent', border: 'none', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                          ☰
                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: 14 }}>
                                                                                                                                                                                                                                                                                                                                                <p style={{ fontFamily: 'Times New Roman', marginTop: 6 }}>
                                                                                                                                                                                                                                                                                                                                                          ZEIROKO is a peer-to-peer banner ad marketplace. Choose a role to continue.
                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                              <div className="card-row" style={{ marginTop: 18 }}>
                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                className="role-card host"
                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setView('host')}
                                                                                                                                                                                                                                                                                                                                                                                                                    role="button"
                                                                                                                                                                                                                                                                                                                                                                                                                              tabIndex={0}
                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="role-icon" aria-hidden>🤝</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 style={{ fontFamily: 'Times New Roman' }}>I'm a Host</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ fontFamily: 'Times New Roman' }}>Become an ambassador — list your profile and price for banner spots.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="role-card advertiser"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setView('advertiser')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            role="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tabIndex={0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="role-icon" aria-hidden>📣</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 style={{ fontFamily: 'Times New Roman' }}>I'm an Advertiser</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ fontFamily: 'Times New Roman' }}>Create a campaign and add banner assets.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flow-area" style={{ marginTop: 22 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loadingProfile ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontFamily: 'Times New Roman' }}>Loading profile…</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : view === 'host' ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <HostForm existing={profile} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : view === 'advertiser' ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdvertiserForm />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontFamily: 'Times New Roman' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <em>Select a role card above to get started.</em>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }